[project]
name = "fastapi-sql-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "sqlalchemy>=2.0.41",
]
